feat: mana_audio
Qbox-project/txAdminRecipe pull request #90
Opened 2024-09-09 04:34 UTC by mafewtm

## Description

there ya go

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-09-09 05:36 UTC, Manason approved these changes

2024-09-13 14:35 UTC, D4isDAVID submitted a review, later dismissed
[Manason/mana_audio releases](https://github.com/Manason/mana_audio/releases) do not seem to provide any file named `mana_audio.zip`. If we *will* add this in the future, Manason has to either provide such a file, or we have to download the source code zip similarly to ox_fuel.

2024-09-13 16:42 UTC, Manason commented
> [Manason/mana_audio releases](https://github.com/Manason/mana_audio/releases) do not seem to provide any file named `mana_audio.zip`. If we _will_ add this in the future, Manason has to either provide such a file, or we have to download the source code zip similarly to ox_fuel.

Yeah, I'm trying to cut a new release with the Qbox release scripts, but running into some errors. Will get out a new release shortly.

2024-09-19 05:31 UTC, solareon requested changes

2024-09-19 05:31 UTC, solareon commented on qbox-lean.yaml
> +    dest: ./resources/[qbx]
```suggestion
    dest: ./resources/[standalone]
```

2024-09-19 05:31 UTC, solareon commented on qbox-stable.yaml
> +    dest: ./resources/[qbx]
```suggestion
    dest: ./resources/[standalone]
```

2024-09-19 05:31 UTC, solareon commented on qbox.yaml
> +    dest: ./resources/[qbx]
```suggestion
    dest: ./resources/[standalone]
```

2024-09-19 05:32 UTC, solareon approved these changes

2024-09-19 05:37 UTC, merged