Fixed items without images, added needed exports to items.lua
Qbox-project/txAdminRecipe pull request #91
Opened 2024-09-12 10:56 UTC by Shizojin

## Description

With default installation, items were not usable (vehiclehandler items).
Added needed exports, also changed picturenaming in items.lua for a few items / changed image names / added images because they were missing.

 Still To-Do: As solareon suggested, get rid of items which aren't needed by default recipe. Just wanted to push this out asap so by default repairkit etc works without issue on unstable recipe and to prevent "repkit" not working messages etc.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-09-12 14:56 UTC, Manason requested changes
ox_fuel v1.4.1+ requires server artifact version 8201+, but qbx_core minimum version is lower than this. We shouldn't update ox_fuel until we raise the minimum core version. Also why not make it latest?

2024-09-12 15:49 UTC, Shizojin commented
> ox_fuel v1.4.1+ requires server artifact version 8201+, but qbx_core minimum version is lower than this. We shouldn't update ox_fuel until we raise the minimum core version. Also why not make it latest?

Didn't know about that much in detail about required and actual artifact version😅 
Why not latest? Just sticked to existing template and made to actual version

Will revert back to 1.4 then because switching to latest also brings the artifact version like you mentioned.

2024-09-12 17:41 UTC, mafewtm commented
This seems unnecessary. Not to mention quite a few of these items are not used at all.

2024-09-12 18:46 UTC, Shizojin commented
> This seems unnecessary. Not to mention quite a few of these items are not used at all.

Actually agree with you on that. Just wanted to make an approach where things which are included in recipe, work out of the box.
Like actual used items, and the vehiclefailure stuff like repairkit etc which need an additional export in items.lua.

But this can be easily postponed until I sorted out items which are actually used in unstable recipe and no unneded items/images are included.

2024-09-13 06:20 UTC, Manason commented
> > This seems unnecessary. Not to mention quite a few of these items are not used at all.
> 
> Actually agree with you on that. Just wanted to make an approach where things which are included in recipe, work out of the box. Like actual used items, and the vehiclefailure stuff like repairkit etc which need an additional export in items.lua.
> 
> But this can be easily postponed until I sorted out items which are actually used in unstable recipe and no unneded items/images are included.

I've marked the PR WIP. Feel free to mark when it's ready for review again.

2025-03-25 14:18 UTC, closed without merging